# Generated by Django 3.2.9 on 2021-12-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Mainprocessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='OriginPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
                ('weight', models.PositiveIntegerField(verbose_name='重量')),
                ('taste', models.TextField(verbose_name='味道')),
                ('description', models.TextField(verbose_name='描述')),
                ('roast', models.CharField(choices=[('Light', '極淺度烘焙'), ('Cinnamon', '淺度烘焙'), ('Medium', '中度烘焙'), ('High', '中度微深烘焙'), ('City', '中深度烘焙'), ('Full-City', '微深度烘焙'), ('French', '極深烘焙'), ('Italian', '極深度烘焙')], max_length=10, verbose_name='烘培程度')),
                ('price', models.PositiveIntegerField(verbose_name='價格')),
                ('discount', models.PositiveIntegerField(verbose_name='優惠價格')),
                ('main_processing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffees.mainprocessing', verbose_name='主要處理法')),
                ('origin_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffees.originplace', verbose_name='產地')),
            ],
        ),
    ]
