# Generated by Django 3.2.9 on 2021-12-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': '咖啡', 'verbose_name_plural': '咖啡'},
        ),
        migrations.AlterModelOptions(
            name='grinding',
            options={'verbose_name': '磨豆方式', 'verbose_name_plural': '磨豆方式'},
        ),
        migrations.AlterModelOptions(
            name='mainprocessing',
            options={'verbose_name': '主要處理法', 'verbose_name_plural': '主要處理法'},
        ),
        migrations.AlterModelOptions(
            name='originplace',
            options={'verbose_name': '產地', 'verbose_name_plural': '產地'},
        ),
    ]
